on: [push]
name: build
jobs:
  runhaskell:
    name: Output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - run: runhaskell src/Main.hs
